package com.shandiangou.tradetestdemo.domain.DO;

import java.util.Date;

public class BizOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.biz_order_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long bizOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.daily_sequence
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer dailySequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.landmark_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long landmarkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.buyer_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.buyer_nick
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String buyerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.item_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.sku_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.item_name
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.total_price
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.buy_amount
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long buyAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.pay_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.logistics_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte logisticsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.logistics_no
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String logisticsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.shipping
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte shipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.refund_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte refundStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.refund_no
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String refundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.attributes
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String attributes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.address_snapshot
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String addressSnapshot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.pay_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.item_pic_url
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String itemPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.invoice_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte invoiceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.invoice_info
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String invoiceInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.pay_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.onlinepay_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte onlinepayType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.buyer2uspay_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long buyer2uspayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.buyer2uspay_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Date buyer2uspayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.order_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.is_deleted
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.gmt_create
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.gmt_modified
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.comment
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.admin_comment
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String adminComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.community_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.community
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String community;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.mobile
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.shop_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.seller_comment
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String sellerComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.send_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.out_order_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String outOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.shop_coupon_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long shopCouponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.unit
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.shop_order_code
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String shopOrderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.feature
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String feature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.come_channel
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer comeChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.reduce_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long reduceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.reduce
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer reduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.last_op_user_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer lastOpUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.scheduled_send_datetime
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Date scheduledSendDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.scheduled_send_lastnotify_datetime
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Date scheduledSendLastnotifyDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.xiaoer_t_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long xiaoerTId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.remote_ip
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String remoteIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.remote_user_agent
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String remoteUserAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.us2sellerpay_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte us2sellerpayStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.us2sellerpay_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long us2sellerpayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.us2sellerpay_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Date us2sellerpayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.shop_coupon_price
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer shopCouponPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.send_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte sendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.area
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.scheduled_send_end_date
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Date scheduledSendEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.order_eval
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte orderEval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.original_price
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Long originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.reject_value
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte rejectValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.reject_reason
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private String rejectReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.confirmed_by_system
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Boolean confirmedBySystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.cancelled_by
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte cancelledBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.lng
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Double lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.lat
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Double lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.trade_success_datetime
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Date tradeSuccessDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.xiaoer_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer xiaoerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.us2sellerpay_blocked_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte us2sellerpayBlockedType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.deliverycode
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer deliverycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.int20_col1
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer int20Col1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.no_reduce_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Short noReduceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.is_accept
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Byte isAccept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.city_code
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    private Integer cityCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.biz_order_id
     *
     * @return the value of biz_order.biz_order_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getBizOrderId() {
        return bizOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.biz_order_id
     *
     * @param bizOrderId the value for biz_order.biz_order_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setBizOrderId(Long bizOrderId) {
        this.bizOrderId = bizOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.daily_sequence
     *
     * @return the value of biz_order.daily_sequence
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getDailySequence() {
        return dailySequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.daily_sequence
     *
     * @param dailySequence the value for biz_order.daily_sequence
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setDailySequence(Integer dailySequence) {
        this.dailySequence = dailySequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.landmark_id
     *
     * @return the value of biz_order.landmark_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getLandmarkId() {
        return landmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.landmark_id
     *
     * @param landmarkId the value for biz_order.landmark_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setLandmarkId(Long landmarkId) {
        this.landmarkId = landmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.buyer_id
     *
     * @return the value of biz_order.buyer_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.buyer_id
     *
     * @param buyerId the value for biz_order.buyer_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.buyer_nick
     *
     * @return the value of biz_order.buyer_nick
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.buyer_nick
     *
     * @param buyerNick the value for biz_order.buyer_nick
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.item_id
     *
     * @return the value of biz_order.item_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.item_id
     *
     * @param itemId the value for biz_order.item_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.sku_id
     *
     * @return the value of biz_order.sku_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.sku_id
     *
     * @param skuId the value for biz_order.sku_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.item_name
     *
     * @return the value of biz_order.item_name
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.item_name
     *
     * @param itemName the value for biz_order.item_name
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.total_price
     *
     * @return the value of biz_order.total_price
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.total_price
     *
     * @param totalPrice the value for biz_order.total_price
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.buy_amount
     *
     * @return the value of biz_order.buy_amount
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getBuyAmount() {
        return buyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.buy_amount
     *
     * @param buyAmount the value for biz_order.buy_amount
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setBuyAmount(Long buyAmount) {
        this.buyAmount = buyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.pay_status
     *
     * @return the value of biz_order.pay_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.pay_status
     *
     * @param payStatus the value for biz_order.pay_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.logistics_status
     *
     * @return the value of biz_order.logistics_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getLogisticsStatus() {
        return logisticsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.logistics_status
     *
     * @param logisticsStatus the value for biz_order.logistics_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setLogisticsStatus(Byte logisticsStatus) {
        this.logisticsStatus = logisticsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.logistics_no
     *
     * @return the value of biz_order.logistics_no
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getLogisticsNo() {
        return logisticsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.logistics_no
     *
     * @param logisticsNo the value for biz_order.logistics_no
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setLogisticsNo(String logisticsNo) {
        this.logisticsNo = logisticsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.shipping
     *
     * @return the value of biz_order.shipping
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getShipping() {
        return shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.shipping
     *
     * @param shipping the value for biz_order.shipping
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setShipping(Byte shipping) {
        this.shipping = shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.status
     *
     * @return the value of biz_order.status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.status
     *
     * @param status the value for biz_order.status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.refund_status
     *
     * @return the value of biz_order.refund_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.refund_status
     *
     * @param refundStatus the value for biz_order.refund_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setRefundStatus(Byte refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.refund_no
     *
     * @return the value of biz_order.refund_no
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getRefundNo() {
        return refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.refund_no
     *
     * @param refundNo the value for biz_order.refund_no
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setRefundNo(String refundNo) {
        this.refundNo = refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.attributes
     *
     * @return the value of biz_order.attributes
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.attributes
     *
     * @param attributes the value for biz_order.attributes
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.address_snapshot
     *
     * @return the value of biz_order.address_snapshot
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getAddressSnapshot() {
        return addressSnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.address_snapshot
     *
     * @param addressSnapshot the value for biz_order.address_snapshot
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setAddressSnapshot(String addressSnapshot) {
        this.addressSnapshot = addressSnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.pay_time
     *
     * @return the value of biz_order.pay_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.pay_time
     *
     * @param payTime the value for biz_order.pay_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.item_pic_url
     *
     * @return the value of biz_order.item_pic_url
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getItemPicUrl() {
        return itemPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.item_pic_url
     *
     * @param itemPicUrl the value for biz_order.item_pic_url
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setItemPicUrl(String itemPicUrl) {
        this.itemPicUrl = itemPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.invoice_type
     *
     * @return the value of biz_order.invoice_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.invoice_type
     *
     * @param invoiceType the value for biz_order.invoice_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setInvoiceType(Byte invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.invoice_info
     *
     * @return the value of biz_order.invoice_info
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getInvoiceInfo() {
        return invoiceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.invoice_info
     *
     * @param invoiceInfo the value for biz_order.invoice_info
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setInvoiceInfo(String invoiceInfo) {
        this.invoiceInfo = invoiceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.pay_type
     *
     * @return the value of biz_order.pay_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.pay_type
     *
     * @param payType the value for biz_order.pay_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.onlinepay_type
     *
     * @return the value of biz_order.onlinepay_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getOnlinepayType() {
        return onlinepayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.onlinepay_type
     *
     * @param onlinepayType the value for biz_order.onlinepay_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setOnlinepayType(Byte onlinepayType) {
        this.onlinepayType = onlinepayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.buyer2uspay_id
     *
     * @return the value of biz_order.buyer2uspay_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getBuyer2uspayId() {
        return buyer2uspayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.buyer2uspay_id
     *
     * @param buyer2uspayId the value for biz_order.buyer2uspay_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setBuyer2uspayId(Long buyer2uspayId) {
        this.buyer2uspayId = buyer2uspayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.buyer2uspay_time
     *
     * @return the value of biz_order.buyer2uspay_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Date getBuyer2uspayTime() {
        return buyer2uspayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.buyer2uspay_time
     *
     * @param buyer2uspayTime the value for biz_order.buyer2uspay_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setBuyer2uspayTime(Date buyer2uspayTime) {
        this.buyer2uspayTime = buyer2uspayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.order_type
     *
     * @return the value of biz_order.order_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.order_type
     *
     * @param orderType the value for biz_order.order_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.is_deleted
     *
     * @return the value of biz_order.is_deleted
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.is_deleted
     *
     * @param isDeleted the value for biz_order.is_deleted
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.gmt_create
     *
     * @return the value of biz_order.gmt_create
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.gmt_create
     *
     * @param gmtCreate the value for biz_order.gmt_create
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.gmt_modified
     *
     * @return the value of biz_order.gmt_modified
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.gmt_modified
     *
     * @param gmtModified the value for biz_order.gmt_modified
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.comment
     *
     * @return the value of biz_order.comment
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.comment
     *
     * @param comment the value for biz_order.comment
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.admin_comment
     *
     * @return the value of biz_order.admin_comment
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getAdminComment() {
        return adminComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.admin_comment
     *
     * @param adminComment the value for biz_order.admin_comment
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setAdminComment(String adminComment) {
        this.adminComment = adminComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.type
     *
     * @return the value of biz_order.type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.type
     *
     * @param type the value for biz_order.type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.community_id
     *
     * @return the value of biz_order.community_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.community_id
     *
     * @param communityId the value for biz_order.community_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setCommunityId(Long communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.community
     *
     * @return the value of biz_order.community
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.community
     *
     * @param community the value for biz_order.community
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setCommunity(String community) {
        this.community = community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.mobile
     *
     * @return the value of biz_order.mobile
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.mobile
     *
     * @param mobile the value for biz_order.mobile
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setMobile(Long mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.shop_id
     *
     * @return the value of biz_order.shop_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.shop_id
     *
     * @param shopId the value for biz_order.shop_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.seller_comment
     *
     * @return the value of biz_order.seller_comment
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getSellerComment() {
        return sellerComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.seller_comment
     *
     * @param sellerComment the value for biz_order.seller_comment
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setSellerComment(String sellerComment) {
        this.sellerComment = sellerComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.send_time
     *
     * @return the value of biz_order.send_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.send_time
     *
     * @param sendTime the value for biz_order.send_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.out_order_id
     *
     * @return the value of biz_order.out_order_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getOutOrderId() {
        return outOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.out_order_id
     *
     * @param outOrderId the value for biz_order.out_order_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setOutOrderId(String outOrderId) {
        this.outOrderId = outOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.shop_coupon_id
     *
     * @return the value of biz_order.shop_coupon_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getShopCouponId() {
        return shopCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.shop_coupon_id
     *
     * @param shopCouponId the value for biz_order.shop_coupon_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setShopCouponId(Long shopCouponId) {
        this.shopCouponId = shopCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.unit
     *
     * @return the value of biz_order.unit
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.unit
     *
     * @param unit the value for biz_order.unit
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.shop_order_code
     *
     * @return the value of biz_order.shop_order_code
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getShopOrderCode() {
        return shopOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.shop_order_code
     *
     * @param shopOrderCode the value for biz_order.shop_order_code
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setShopOrderCode(String shopOrderCode) {
        this.shopOrderCode = shopOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.feature
     *
     * @return the value of biz_order.feature
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.feature
     *
     * @param feature the value for biz_order.feature
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setFeature(String feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.come_channel
     *
     * @return the value of biz_order.come_channel
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getComeChannel() {
        return comeChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.come_channel
     *
     * @param comeChannel the value for biz_order.come_channel
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setComeChannel(Integer comeChannel) {
        this.comeChannel = comeChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.reduce_id
     *
     * @return the value of biz_order.reduce_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getReduceId() {
        return reduceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.reduce_id
     *
     * @param reduceId the value for biz_order.reduce_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setReduceId(Long reduceId) {
        this.reduceId = reduceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.reduce
     *
     * @return the value of biz_order.reduce
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getReduce() {
        return reduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.reduce
     *
     * @param reduce the value for biz_order.reduce
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setReduce(Integer reduce) {
        this.reduce = reduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.last_op_user_id
     *
     * @return the value of biz_order.last_op_user_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getLastOpUserId() {
        return lastOpUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.last_op_user_id
     *
     * @param lastOpUserId the value for biz_order.last_op_user_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setLastOpUserId(Integer lastOpUserId) {
        this.lastOpUserId = lastOpUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.scheduled_send_datetime
     *
     * @return the value of biz_order.scheduled_send_datetime
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Date getScheduledSendDatetime() {
        return scheduledSendDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.scheduled_send_datetime
     *
     * @param scheduledSendDatetime the value for biz_order.scheduled_send_datetime
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setScheduledSendDatetime(Date scheduledSendDatetime) {
        this.scheduledSendDatetime = scheduledSendDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.scheduled_send_lastnotify_datetime
     *
     * @return the value of biz_order.scheduled_send_lastnotify_datetime
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Date getScheduledSendLastnotifyDatetime() {
        return scheduledSendLastnotifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.scheduled_send_lastnotify_datetime
     *
     * @param scheduledSendLastnotifyDatetime the value for biz_order.scheduled_send_lastnotify_datetime
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setScheduledSendLastnotifyDatetime(Date scheduledSendLastnotifyDatetime) {
        this.scheduledSendLastnotifyDatetime = scheduledSendLastnotifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.xiaoer_t_id
     *
     * @return the value of biz_order.xiaoer_t_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getXiaoerTId() {
        return xiaoerTId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.xiaoer_t_id
     *
     * @param xiaoerTId the value for biz_order.xiaoer_t_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setXiaoerTId(Long xiaoerTId) {
        this.xiaoerTId = xiaoerTId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.remote_ip
     *
     * @return the value of biz_order.remote_ip
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getRemoteIp() {
        return remoteIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.remote_ip
     *
     * @param remoteIp the value for biz_order.remote_ip
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.remote_user_agent
     *
     * @return the value of biz_order.remote_user_agent
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getRemoteUserAgent() {
        return remoteUserAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.remote_user_agent
     *
     * @param remoteUserAgent the value for biz_order.remote_user_agent
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setRemoteUserAgent(String remoteUserAgent) {
        this.remoteUserAgent = remoteUserAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.us2sellerpay_status
     *
     * @return the value of biz_order.us2sellerpay_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getUs2sellerpayStatus() {
        return us2sellerpayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.us2sellerpay_status
     *
     * @param us2sellerpayStatus the value for biz_order.us2sellerpay_status
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setUs2sellerpayStatus(Byte us2sellerpayStatus) {
        this.us2sellerpayStatus = us2sellerpayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.us2sellerpay_id
     *
     * @return the value of biz_order.us2sellerpay_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getUs2sellerpayId() {
        return us2sellerpayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.us2sellerpay_id
     *
     * @param us2sellerpayId the value for biz_order.us2sellerpay_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setUs2sellerpayId(Long us2sellerpayId) {
        this.us2sellerpayId = us2sellerpayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.us2sellerpay_time
     *
     * @return the value of biz_order.us2sellerpay_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Date getUs2sellerpayTime() {
        return us2sellerpayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.us2sellerpay_time
     *
     * @param us2sellerpayTime the value for biz_order.us2sellerpay_time
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setUs2sellerpayTime(Date us2sellerpayTime) {
        this.us2sellerpayTime = us2sellerpayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.shop_coupon_price
     *
     * @return the value of biz_order.shop_coupon_price
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getShopCouponPrice() {
        return shopCouponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.shop_coupon_price
     *
     * @param shopCouponPrice the value for biz_order.shop_coupon_price
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setShopCouponPrice(Integer shopCouponPrice) {
        this.shopCouponPrice = shopCouponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.send_type
     *
     * @return the value of biz_order.send_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.send_type
     *
     * @param sendType the value for biz_order.send_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setSendType(Byte sendType) {
        this.sendType = sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.area
     *
     * @return the value of biz_order.area
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.area
     *
     * @param area the value for biz_order.area
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.scheduled_send_end_date
     *
     * @return the value of biz_order.scheduled_send_end_date
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Date getScheduledSendEndDate() {
        return scheduledSendEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.scheduled_send_end_date
     *
     * @param scheduledSendEndDate the value for biz_order.scheduled_send_end_date
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setScheduledSendEndDate(Date scheduledSendEndDate) {
        this.scheduledSendEndDate = scheduledSendEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.order_eval
     *
     * @return the value of biz_order.order_eval
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getOrderEval() {
        return orderEval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.order_eval
     *
     * @param orderEval the value for biz_order.order_eval
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setOrderEval(Byte orderEval) {
        this.orderEval = orderEval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.original_price
     *
     * @return the value of biz_order.original_price
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Long getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.original_price
     *
     * @param originalPrice the value for biz_order.original_price
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setOriginalPrice(Long originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.reject_value
     *
     * @return the value of biz_order.reject_value
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getRejectValue() {
        return rejectValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.reject_value
     *
     * @param rejectValue the value for biz_order.reject_value
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setRejectValue(Byte rejectValue) {
        this.rejectValue = rejectValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.reject_reason
     *
     * @return the value of biz_order.reject_reason
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.reject_reason
     *
     * @param rejectReason the value for biz_order.reject_reason
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.confirmed_by_system
     *
     * @return the value of biz_order.confirmed_by_system
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Boolean getConfirmedBySystem() {
        return confirmedBySystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.confirmed_by_system
     *
     * @param confirmedBySystem the value for biz_order.confirmed_by_system
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setConfirmedBySystem(Boolean confirmedBySystem) {
        this.confirmedBySystem = confirmedBySystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.cancelled_by
     *
     * @return the value of biz_order.cancelled_by
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getCancelledBy() {
        return cancelledBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.cancelled_by
     *
     * @param cancelledBy the value for biz_order.cancelled_by
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setCancelledBy(Byte cancelledBy) {
        this.cancelledBy = cancelledBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.lng
     *
     * @return the value of biz_order.lng
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.lng
     *
     * @param lng the value for biz_order.lng
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.lat
     *
     * @return the value of biz_order.lat
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.lat
     *
     * @param lat the value for biz_order.lat
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.trade_success_datetime
     *
     * @return the value of biz_order.trade_success_datetime
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Date getTradeSuccessDatetime() {
        return tradeSuccessDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.trade_success_datetime
     *
     * @param tradeSuccessDatetime the value for biz_order.trade_success_datetime
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setTradeSuccessDatetime(Date tradeSuccessDatetime) {
        this.tradeSuccessDatetime = tradeSuccessDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.xiaoer_id
     *
     * @return the value of biz_order.xiaoer_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getXiaoerId() {
        return xiaoerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.xiaoer_id
     *
     * @param xiaoerId the value for biz_order.xiaoer_id
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setXiaoerId(Integer xiaoerId) {
        this.xiaoerId = xiaoerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.us2sellerpay_blocked_type
     *
     * @return the value of biz_order.us2sellerpay_blocked_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getUs2sellerpayBlockedType() {
        return us2sellerpayBlockedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.us2sellerpay_blocked_type
     *
     * @param us2sellerpayBlockedType the value for biz_order.us2sellerpay_blocked_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setUs2sellerpayBlockedType(Byte us2sellerpayBlockedType) {
        this.us2sellerpayBlockedType = us2sellerpayBlockedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.deliverycode
     *
     * @return the value of biz_order.deliverycode
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getDeliverycode() {
        return deliverycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.deliverycode
     *
     * @param deliverycode the value for biz_order.deliverycode
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setDeliverycode(Integer deliverycode) {
        this.deliverycode = deliverycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.int20_col1
     *
     * @return the value of biz_order.int20_col1
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getInt20Col1() {
        return int20Col1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.int20_col1
     *
     * @param int20Col1 the value for biz_order.int20_col1
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setInt20Col1(Integer int20Col1) {
        this.int20Col1 = int20Col1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.no_reduce_type
     *
     * @return the value of biz_order.no_reduce_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Short getNoReduceType() {
        return noReduceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.no_reduce_type
     *
     * @param noReduceType the value for biz_order.no_reduce_type
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setNoReduceType(Short noReduceType) {
        this.noReduceType = noReduceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.is_accept
     *
     * @return the value of biz_order.is_accept
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Byte getIsAccept() {
        return isAccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.is_accept
     *
     * @param isAccept the value for biz_order.is_accept
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setIsAccept(Byte isAccept) {
        this.isAccept = isAccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.city_code
     *
     * @return the value of biz_order.city_code
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public Integer getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.city_code
     *
     * @param cityCode the value for biz_order.city_code
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }
}