package com.shandiangou.tradetestdemo.domain.DO;

import java.util.Date;

public class SubBizOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.biz_order_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long bizOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.pay_order_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long payOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.buyer_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.buyer_nick
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String buyerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.seller_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.seller_nick
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String sellerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.item_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.landmark_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long landmarkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.item_name
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.item_price
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long itemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.buy_amount
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long buyAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.pay_status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Byte payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.logistics_status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Byte logisticsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.logistics_no
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String logisticsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.shipping
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Byte shipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.refund_status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Byte refundStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.refund_no
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String refundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.attributes
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String attributes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.address_snapshot
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String addressSnapshot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.pay_time
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.item_pic_url
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String itemPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.invoice_type
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Byte invoiceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.invoice_info
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String invoiceInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.pay_type
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Byte payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.is_deleted
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.gmt_create
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.gmt_modified
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.comment
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.admin_comment
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String adminComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.type
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.parent_order_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long parentOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.shop_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.total_price
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.mobile
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.community_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.feature
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String feature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.property
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.unit
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.supplier_code
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private String supplierCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.delivery_mode
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Short deliveryMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.pay_amount
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_biz_order.deduct_amount
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    private Long deductAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.biz_order_id
     *
     * @return the value of sub_biz_order.biz_order_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getBizOrderId() {
        return bizOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.biz_order_id
     *
     * @param bizOrderId the value for sub_biz_order.biz_order_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setBizOrderId(Long bizOrderId) {
        this.bizOrderId = bizOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.pay_order_id
     *
     * @return the value of sub_biz_order.pay_order_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.pay_order_id
     *
     * @param payOrderId the value for sub_biz_order.pay_order_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setPayOrderId(Long payOrderId) {
        this.payOrderId = payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.buyer_id
     *
     * @return the value of sub_biz_order.buyer_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.buyer_id
     *
     * @param buyerId the value for sub_biz_order.buyer_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.buyer_nick
     *
     * @return the value of sub_biz_order.buyer_nick
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.buyer_nick
     *
     * @param buyerNick the value for sub_biz_order.buyer_nick
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.seller_id
     *
     * @return the value of sub_biz_order.seller_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.seller_id
     *
     * @param sellerId the value for sub_biz_order.seller_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.seller_nick
     *
     * @return the value of sub_biz_order.seller_nick
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.seller_nick
     *
     * @param sellerNick the value for sub_biz_order.seller_nick
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.item_id
     *
     * @return the value of sub_biz_order.item_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.item_id
     *
     * @param itemId the value for sub_biz_order.item_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.landmark_id
     *
     * @return the value of sub_biz_order.landmark_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getLandmarkId() {
        return landmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.landmark_id
     *
     * @param landmarkId the value for sub_biz_order.landmark_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setLandmarkId(Long landmarkId) {
        this.landmarkId = landmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.item_name
     *
     * @return the value of sub_biz_order.item_name
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.item_name
     *
     * @param itemName the value for sub_biz_order.item_name
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.item_price
     *
     * @return the value of sub_biz_order.item_price
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.item_price
     *
     * @param itemPrice the value for sub_biz_order.item_price
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setItemPrice(Long itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.buy_amount
     *
     * @return the value of sub_biz_order.buy_amount
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getBuyAmount() {
        return buyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.buy_amount
     *
     * @param buyAmount the value for sub_biz_order.buy_amount
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setBuyAmount(Long buyAmount) {
        this.buyAmount = buyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.pay_status
     *
     * @return the value of sub_biz_order.pay_status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.pay_status
     *
     * @param payStatus the value for sub_biz_order.pay_status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.logistics_status
     *
     * @return the value of sub_biz_order.logistics_status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Byte getLogisticsStatus() {
        return logisticsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.logistics_status
     *
     * @param logisticsStatus the value for sub_biz_order.logistics_status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setLogisticsStatus(Byte logisticsStatus) {
        this.logisticsStatus = logisticsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.logistics_no
     *
     * @return the value of sub_biz_order.logistics_no
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getLogisticsNo() {
        return logisticsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.logistics_no
     *
     * @param logisticsNo the value for sub_biz_order.logistics_no
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setLogisticsNo(String logisticsNo) {
        this.logisticsNo = logisticsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.shipping
     *
     * @return the value of sub_biz_order.shipping
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Byte getShipping() {
        return shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.shipping
     *
     * @param shipping the value for sub_biz_order.shipping
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setShipping(Byte shipping) {
        this.shipping = shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.status
     *
     * @return the value of sub_biz_order.status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.status
     *
     * @param status the value for sub_biz_order.status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.refund_status
     *
     * @return the value of sub_biz_order.refund_status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Byte getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.refund_status
     *
     * @param refundStatus the value for sub_biz_order.refund_status
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setRefundStatus(Byte refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.refund_no
     *
     * @return the value of sub_biz_order.refund_no
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getRefundNo() {
        return refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.refund_no
     *
     * @param refundNo the value for sub_biz_order.refund_no
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setRefundNo(String refundNo) {
        this.refundNo = refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.attributes
     *
     * @return the value of sub_biz_order.attributes
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.attributes
     *
     * @param attributes the value for sub_biz_order.attributes
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.address_snapshot
     *
     * @return the value of sub_biz_order.address_snapshot
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getAddressSnapshot() {
        return addressSnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.address_snapshot
     *
     * @param addressSnapshot the value for sub_biz_order.address_snapshot
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setAddressSnapshot(String addressSnapshot) {
        this.addressSnapshot = addressSnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.pay_time
     *
     * @return the value of sub_biz_order.pay_time
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.pay_time
     *
     * @param payTime the value for sub_biz_order.pay_time
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.item_pic_url
     *
     * @return the value of sub_biz_order.item_pic_url
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getItemPicUrl() {
        return itemPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.item_pic_url
     *
     * @param itemPicUrl the value for sub_biz_order.item_pic_url
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setItemPicUrl(String itemPicUrl) {
        this.itemPicUrl = itemPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.invoice_type
     *
     * @return the value of sub_biz_order.invoice_type
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Byte getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.invoice_type
     *
     * @param invoiceType the value for sub_biz_order.invoice_type
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setInvoiceType(Byte invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.invoice_info
     *
     * @return the value of sub_biz_order.invoice_info
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getInvoiceInfo() {
        return invoiceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.invoice_info
     *
     * @param invoiceInfo the value for sub_biz_order.invoice_info
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setInvoiceInfo(String invoiceInfo) {
        this.invoiceInfo = invoiceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.pay_type
     *
     * @return the value of sub_biz_order.pay_type
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.pay_type
     *
     * @param payType the value for sub_biz_order.pay_type
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.is_deleted
     *
     * @return the value of sub_biz_order.is_deleted
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.is_deleted
     *
     * @param isDeleted the value for sub_biz_order.is_deleted
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.gmt_create
     *
     * @return the value of sub_biz_order.gmt_create
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.gmt_create
     *
     * @param gmtCreate the value for sub_biz_order.gmt_create
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.gmt_modified
     *
     * @return the value of sub_biz_order.gmt_modified
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.gmt_modified
     *
     * @param gmtModified the value for sub_biz_order.gmt_modified
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.comment
     *
     * @return the value of sub_biz_order.comment
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.comment
     *
     * @param comment the value for sub_biz_order.comment
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.admin_comment
     *
     * @return the value of sub_biz_order.admin_comment
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getAdminComment() {
        return adminComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.admin_comment
     *
     * @param adminComment the value for sub_biz_order.admin_comment
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setAdminComment(String adminComment) {
        this.adminComment = adminComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.type
     *
     * @return the value of sub_biz_order.type
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.type
     *
     * @param type the value for sub_biz_order.type
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.parent_order_id
     *
     * @return the value of sub_biz_order.parent_order_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getParentOrderId() {
        return parentOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.parent_order_id
     *
     * @param parentOrderId the value for sub_biz_order.parent_order_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setParentOrderId(Long parentOrderId) {
        this.parentOrderId = parentOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.shop_id
     *
     * @return the value of sub_biz_order.shop_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.shop_id
     *
     * @param shopId the value for sub_biz_order.shop_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.total_price
     *
     * @return the value of sub_biz_order.total_price
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.total_price
     *
     * @param totalPrice the value for sub_biz_order.total_price
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.mobile
     *
     * @return the value of sub_biz_order.mobile
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.mobile
     *
     * @param mobile the value for sub_biz_order.mobile
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.community_id
     *
     * @return the value of sub_biz_order.community_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.community_id
     *
     * @param communityId the value for sub_biz_order.community_id
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setCommunityId(Long communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.feature
     *
     * @return the value of sub_biz_order.feature
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.feature
     *
     * @param feature the value for sub_biz_order.feature
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setFeature(String feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.property
     *
     * @return the value of sub_biz_order.property
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.property
     *
     * @param property the value for sub_biz_order.property
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setProperty(String property) {
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.unit
     *
     * @return the value of sub_biz_order.unit
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.unit
     *
     * @param unit the value for sub_biz_order.unit
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.supplier_code
     *
     * @return the value of sub_biz_order.supplier_code
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.supplier_code
     *
     * @param supplierCode the value for sub_biz_order.supplier_code
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.delivery_mode
     *
     * @return the value of sub_biz_order.delivery_mode
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Short getDeliveryMode() {
        return deliveryMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.delivery_mode
     *
     * @param deliveryMode the value for sub_biz_order.delivery_mode
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setDeliveryMode(Short deliveryMode) {
        this.deliveryMode = deliveryMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.pay_amount
     *
     * @return the value of sub_biz_order.pay_amount
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.pay_amount
     *
     * @param payAmount the value for sub_biz_order.pay_amount
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setPayAmount(Long payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_biz_order.deduct_amount
     *
     * @return the value of sub_biz_order.deduct_amount
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public Long getDeductAmount() {
        return deductAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_biz_order.deduct_amount
     *
     * @param deductAmount the value for sub_biz_order.deduct_amount
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    public void setDeductAmount(Long deductAmount) {
        this.deductAmount = deductAmount;
    }
}