package com.shandiangou.tradetestdemo.mapper;

import com.shandiangou.tradetestdemo.domain.DO.BizOrder;
import com.shandiangou.tradetestdemo.domain.DO.BizOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    long countByExample(BizOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    int deleteByExample(BizOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    int deleteByPrimaryKey(Long bizOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    int insert(BizOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    int insertSelective(BizOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    List<BizOrder> selectByExample(BizOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    BizOrder selectByPrimaryKey(Long bizOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    int updateByExampleSelective(@Param("row") BizOrder row, @Param("example") BizOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    int updateByExample(@Param("row") BizOrder row, @Param("example") BizOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    int updateByPrimaryKeySelective(BizOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_order
     *
     * @mbg.generated Thu Nov 10 18:31:30 CST 2022
     */
    int updateByPrimaryKey(BizOrder row);
}