package com.shandiangou.tradetestdemo.mapper;

import com.shandiangou.tradetestdemo.domain.DO.SubBizOrder;
import com.shandiangou.tradetestdemo.domain.DO.SubBizOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubBizOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    long countByExample(SubBizOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    int deleteByExample(SubBizOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    int deleteByPrimaryKey(Long bizOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    int insert(SubBizOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    int insertSelective(SubBizOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    List<SubBizOrder> selectByExample(SubBizOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    SubBizOrder selectByPrimaryKey(Long bizOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    int updateByExampleSelective(@Param("row") SubBizOrder row, @Param("example") SubBizOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    int updateByExample(@Param("row") SubBizOrder row, @Param("example") SubBizOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    int updateByPrimaryKeySelective(SubBizOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_biz_order
     *
     * @mbg.generated Thu Nov 17 16:04:39 CST 2022
     */
    int updateByPrimaryKey(SubBizOrder row);
}